language: node_js

node_js:
  - "4.2.3"

install:
  - npm install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver

script:
  - grunt examples
  - grunt test
  - grunt coveralls:karma_tests
